# A standard Supabase project configured to use Auth
# https://supabase.com/docs/guides/cli/getting-started

[project]
id = "apfiwfkpdhslfavnncsl"  # Development project ID

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15
pooler_enabled = false

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://telbot-dev.onrender.com/auth/callback",
  "https://telbot-staging.onrender.com/auth/callback",
  "https://telbot-production.onrender.com/auth/callback"
]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[analytics]
enabled = false

# Remote configurations for different environments
[remotes.production]
project_id = "prtfkiodnbogqfcztruj"
url = "https://prtfkiodnbogqfcztruj.supabase.co"

[remotes.staging]
# Will be created as a branch from production
seed_script = "./supabase/seeds/staging.sql"

[remotes.development]
# Current development project
project_id = "apfiwfkpdhslfavnncsl"
url = "https://apfiwfkpdhslfavnncsl.supabase.co"
seed_script = "./supabase/seeds/development.sql"

# Function configuration
[functions]
node_version = 20

# Database settings
[db.pooler]
enabled = true
default_pool_size = 25
max_pool_size = 50