# Supabase Configuration for CI/CD

[project]
# Production project
id = "prtfkiodnbogqfcztruj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://telbot-production.onrender.com",
  "https://telbot-staging.onrender.com",
  "https://telbot-dev.onrender.com"
]
jwt_secret = "super-secret-jwt-token"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false
enable_confirmations = false

[storage]
enabled = true

[studio]
enabled = true
port = 54323

# Branch-specific configurations
[remotes.production]
project_id = "prtfkiodnbogqfcztruj"

[remotes.development]
project_id = "apfiwfkpdhslfavnncsl"

# Function configuration
[functions]
node_version = 18

# Observability
[analytics]
enabled = false

# Experimental features
[experimental]
webhooks_enabled = true
