# Database Backup Configuration
# Part of The Progress Method v1.0 - Phase 0 Prep
# WORKER_1 PREP-001D: Database Safety Infrastructure

# Backup General Settings
backup:
  version: "1.0.0"
  enabled: true
  default_environment: "development"
  
# Environment-Specific Backup Configuration
environments:
  development:
    enabled: true
    connection_string: null  # Set via environment variable
    backup_path: "../backups/development"
    compression: true
    compression_level: 6
    encryption: false  # Phase 0 Prep - simplified
    verify_backup: true
    
    # Retention Settings
    retention:
      daily_backups: 7
      weekly_backups: 4
      monthly_backups: 6
      max_backup_size_gb: 5
      cleanup_enabled: true
      
    # What to backup
    include:
      schema: true
      data: true
      indexes: true
      functions: true
      triggers: true
      views: true
      
    exclude:
      tables: []
      schemas: ["information_schema", "pg_catalog"]
      
  staging:
    enabled: false  # Phase 0 Prep - disabled for safety
    connection_string: null
    backup_path: "../backups/staging"
    compression: true
    compression_level: 9
    encryption: true
    verify_backup: true
    
    retention:
      daily_backups: 14
      weekly_backups: 8
      monthly_backups: 12
      max_backup_size_gb: 20
      cleanup_enabled: true
      
    include:
      schema: true
      data: true
      indexes: true
      functions: true
      triggers: true
      views: true
      
    exclude:
      tables: ["temp_*", "cache_*"]
      schemas: ["information_schema", "pg_catalog"]
      
  production:
    enabled: false  # Phase 0 Prep - disabled for safety
    connection_string: null
    backup_path: "../backups/production"
    compression: true
    compression_level: 9
    encryption: true
    verify_backup: true
    
    retention:
      daily_backups: 30
      weekly_backups: 12
      monthly_backups: 24
      max_backup_size_gb: 100
      cleanup_enabled: true
      
    include:
      schema: true
      data: true
      indexes: true
      functions: true
      triggers: true
      views: true
      
    exclude:
      tables: ["audit_temp", "session_*"]
      schemas: ["information_schema", "pg_catalog"]

# Backup Scheduling
schedules:
  development:
    enabled: true
    frequency: "daily"
    time: "02:00"
    timezone: "UTC"
    max_concurrent: 1
    
  staging:
    enabled: false
    frequency: "daily"
    time: "01:00"
    timezone: "UTC"
    max_concurrent: 1
    
  production:
    enabled: false
    frequency: "daily"
    time: "00:30"
    timezone: "UTC"
    max_concurrent: 2

# Backup Types and Options
backup_types:
  full:
    enabled: true
    frequency: "daily"
    compression: true
    verify: true
    
  incremental:
    enabled: false  # Phase 0 Prep - simplified
    frequency: "hourly"
    requires_full_backup: true
    
  differential:
    enabled: false  # Phase 0 Prep - simplified
    frequency: "hourly"
    requires_full_backup: true

# Backup Validation
validation:
  enabled: true
  verify_integrity: true
  check_file_size: true
  validate_compression: true
  test_restore_ability: false  # Phase 0 Prep - mock only
  
  checks:
    file_exists: true
    file_size_minimum: 1024  # 1KB minimum
    checksum_verification: true
    compression_ratio: true
    
  thresholds:
    min_backup_size_bytes: 1024
    max_compression_ratio: 0.1
    max_backup_time_minutes: 60

# Emergency Backup Triggers
emergency_triggers:
  enabled: true
  
  triggers:
    pre_migration: true
    pre_deployment: true
    critical_error: true
    manual_request: true
    system_maintenance: true
    
  settings:
    immediate_execution: true
    override_schedule: true
    priority_level: "high"
    retention_override: 90  # days

# Backup Storage and Management
storage:
  local:
    enabled: true
    base_path: "../backups"
    permissions: "0750"
    
  remote:
    enabled: false  # Phase 0 Prep - simplified
    provider: null
    bucket: null
    credentials: null
    
  cleanup:
    enabled: true
    run_after_backup: true
    log_cleanup_actions: true

# Backup Naming and Organization
naming:
  pattern: "{environment}_{timestamp}_{type}"
  timestamp_format: "%Y%m%d_%H%M%S"
  include_hostname: false  # Phase 0 Prep
  include_version: true
  
  directories:
    by_environment: true
    by_date: true
    by_type: false

# Performance and Resource Management
performance:
  max_parallel_backups: 1
  io_nice_level: 7
  cpu_nice_level: 10
  
  limits:
    max_memory_mb: 1024
    max_io_bandwidth_mb: 50
    timeout_minutes: 120
    
  optimization:
    use_compression: true
    parallel_compression: false  # Phase 0 Prep
    incremental_backups: false  # Phase 0 Prep

# Monitoring and Alerting
monitoring:
  enabled: true
  log_all_operations: true
  track_performance: true
  
  metrics:
    backup_duration: true
    backup_size: true
    compression_ratio: true
    success_rate: true
    
  alerting:
    enabled: false  # Phase 0 Prep
    on_failure: false
    on_timeout: false
    on_size_anomaly: false

# Security and Access Control
security:
  encrypt_backups: false  # Phase 0 Prep - simplified
  secure_file_permissions: true
  audit_backup_access: true
  
  access_control:
    restrict_backup_access: true
    require_authentication: false  # Phase 0 Prep
    log_access_attempts: true

# Integration with Orchestra System
orchestration:
  enabled: true
  log_to_orchestra: true
  report_status: true
  
  communication:
    status_updates: true
    progress_reporting: true
    error_notification: true
    completion_notification: true

# Mock Operations for Phase 0 Prep
mock_operations:
  enabled: true
  simulate_real_backups: true
  generate_mock_files: true
  realistic_timing: true
  
  simulation:
    backup_duration_range: [10, 60]  # seconds
    file_size_range: [1024, 10485760]  # 1KB to 10MB
    success_rate: 0.95
    
  safety:
    no_real_database_access: true
    no_real_file_operations: false  # Need to create actual backup files for validation
    log_mock_operations: true