# Database Safety Infrastructure Configuration
# Part of The Progress Method v1.0 - Phase 0 Prep
# WORKER_1 PREP-001D: Database Safety Infrastructure

# Global Settings
global:
  version: "1.0.0"
  environment: "development"
  debug_mode: true
  log_level: "INFO"
  
# Database Environments Configuration
environments:
  development:
    enabled: true
    backup_required: true
    migration_validation: true
    rollback_testing: true
    connection_pooling: true
    ssl_required: false
    max_connections: 10
    connection_timeout: 30
    
  staging:
    enabled: false  # Phase 0 Prep - disabled for safety
    backup_required: true
    migration_validation: true
    rollback_testing: true
    connection_pooling: true
    ssl_required: true
    max_connections: 20
    connection_timeout: 30
    
  production:
    enabled: false  # Phase 0 Prep - disabled for safety
    backup_required: true
    migration_validation: true
    rollback_testing: true
    connection_pooling: true
    ssl_required: true
    max_connections: 50
    connection_timeout: 30

# Backup Configuration
backup:
  enabled: true
  compression: true
  encryption: false  # Phase 0 Prep - simplified
  retention_days: 30
  verify_integrity: true
  include_schema: true
  include_data: true
  exclude_tables: []
  max_backup_size_gb: 10
  backup_location: "../backups"
  
  schedules:
    development:
      frequency: "daily"
      time: "02:00"
      enabled: true
    staging:
      frequency: "daily"
      time: "01:00"
      enabled: false
    production:
      frequency: "daily"
      time: "00:30"
      enabled: false

# Migration Configuration
migration:
  enabled: true
  validation_required: true
  rollback_script_required: true
  approval_required: false  # Phase 0 Prep
  backup_before_migration: true
  test_migration_first: true
  
  validation_rules:
    check_syntax: true
    check_destructive_operations: true
    validate_dependencies: true
    require_transaction_handling: true
    check_impact_assessment: true
    
  destructive_operations:
    - "DROP TABLE"
    - "DROP COLUMN" 
    - "DROP INDEX"
    - "TRUNCATE"
    - "DELETE FROM"
    - "ALTER TABLE.*DROP"
    
  approval_workflow:
    development:
      required: false
      auto_approve: true
    staging:
      required: true
      auto_approve: false
    production:
      required: true
      auto_approve: false

# Rollback Configuration
rollback:
  enabled: true
  auto_rollback_on_failure: true
  backup_before_rollback: true
  validation_after_rollback: true
  max_rollback_time_minutes: 30
  require_confirmation: true
  
  triggers:
    migration_failure: true
    critical_error: true
    manual_request: true
    
  safety_checks:
    verify_rollback_script: true
    validate_environment: true
    check_dependencies: true

# Connection Management
connections:
  pooling_enabled: true
  health_check_enabled: true
  timeout_handling: true
  ssl_validation: true
  credential_validation: true
  
  pool_settings:
    min_connections: 2
    max_connections: 10
    connection_timeout: 30
    idle_timeout: 300
    
  security:
    require_ssl_production: true
    validate_certificates: true
    encrypt_credentials: false  # Phase 0 Prep - simplified
    audit_connections: true
    
  monitoring:
    log_connections: true
    track_performance: true
    alert_on_failures: true
    health_check_interval: 60

# Safety and Security
safety:
  phase_0_prep_mode: true
  mock_operations: true
  real_database_operations: false
  emergency_stop_enabled: true
  
  checks:
    validate_environment: true
    check_locks: true
    verify_permissions: true
    audit_operations: true
    
  emergency_procedures:
    auto_backup_on_critical_error: true
    rollback_on_failure: true
    notification_enabled: false  # Phase 0 Prep
    stop_on_multiple_failures: true

# Logging and Monitoring
logging:
  enabled: true
  level: "INFO"
  file_rotation: true
  max_file_size_mb: 100
  backup_count: 5
  
  targets:
    file: true
    console: true
    database: false  # Phase 0 Prep
    
  categories:
    backup_operations: true
    migration_operations: true
    rollback_operations: true
    connection_management: true
    security_events: true
    performance_metrics: true

# Orchestration Integration
orchestration:
  enabled: true
  worker_id: "WORKER_1"
  task_id: "PREP-001D"
  log_to_orchestra: true
  report_progress: true
  
  boundaries:
    respect_phase_limits: true
    validate_permissions: true
    check_locks: true
    
  communication:
    status_updates: true
    error_reporting: true
    completion_notification: true

# Performance and Optimization
performance:
  query_timeout: 30
  slow_query_threshold: 5.0
  connection_retry_attempts: 3
  retry_delay_seconds: 1
  
  optimization:
    connection_pooling: true
    query_caching: false  # Phase 0 Prep
    index_optimization: false  # Phase 0 Prep
    
  monitoring:
    track_query_performance: true
    log_slow_queries: true
    alert_on_timeouts: true

# Testing and Validation
testing:
  enabled: true
  comprehensive_tests: true
  performance_tests: true
  security_tests: true
  
  test_environments:
    development: true
    staging: false  # Phase 0 Prep
    production: false  # Phase 0 Prep
    
  mock_testing:
    simulate_real_operations: true
    generate_realistic_data: true
    test_error_conditions: true
    
  validation:
    connection_tests: true
    backup_validation: true
    migration_testing: true
    rollback_testing: true