# Database Migration Configuration
# Part of The Progress Method v1.0 - Phase 0 Prep
# WORKER_1 PREP-001D: Database Safety Infrastructure

# Migration General Settings
migration:
  version: "1.0.0"
  enabled: true
  default_environment: "development"
  mock_mode: true  # Phase 0 Prep safety

# Environment-Specific Migration Configuration
environments:
  development:
    enabled: true
    strict_validation: false
    allow_destructive: true
    require_approval: false
    auto_backup: true
    test_rollback: true
    
    validation:
      syntax_check: true
      impact_assessment: true
      dependency_check: true
      rollback_script_required: true
      
    safety:
      backup_before_migration: true
      validate_before_execution: true
      test_migration_first: false  # Phase 0 Prep
      
  staging:
    enabled: false  # Phase 0 Prep - disabled for safety
    strict_validation: true
    allow_destructive: true
    require_approval: true
    auto_backup: true
    test_rollback: true
    
    validation:
      syntax_check: true
      impact_assessment: true
      dependency_check: true
      rollback_script_required: true
      
    safety:
      backup_before_migration: true
      validate_before_execution: true
      test_migration_first: true
      
  production:
    enabled: false  # Phase 0 Prep - disabled for safety
    strict_validation: true
    allow_destructive: false
    require_approval: true
    auto_backup: true
    test_rollback: true
    
    validation:
      syntax_check: true
      impact_assessment: true
      dependency_check: true
      rollback_script_required: true
      
    safety:
      backup_before_migration: true
      validate_before_execution: true
      test_migration_first: true

# Migration Validation Rules
validation_rules:
  enabled: true
  
  basic_checks:
    file_exists: true
    file_readable: true
    non_empty_content: true
    valid_encoding: true
    
  syntax_validation:
    enabled: true
    check_sql_syntax: true
    validate_statements: true
    check_balanced_quotes: true
    check_balanced_parentheses: true
    
  content_validation:
    require_transaction_handling: true
    check_begin_commit: true
    validate_rollback_available: true
    
  security_validation:
    check_destructive_operations: true
    validate_permissions: true
    check_injection_patterns: false  # Phase 0 Prep - simplified

# Destructive Operations Detection
destructive_operations:
  patterns:
    - "DROP\\s+TABLE"
    - "DROP\\s+COLUMN"
    - "DROP\\s+INDEX"
    - "DROP\\s+CONSTRAINT"
    - "DROP\\s+FUNCTION"
    - "DROP\\s+VIEW"
    - "TRUNCATE\\s+TABLE"
    - "DELETE\\s+FROM"
    - "ALTER\\s+TABLE.*DROP"
    - "ALTER\\s+COLUMN.*DROP"
    
  handling:
    development:
      allow: true
      warn: true
      require_confirmation: false
      
    staging:
      allow: true
      warn: true
      require_confirmation: true
      
    production:
      allow: false
      warn: true
      require_confirmation: true

# Required Patterns for Migration Scripts
required_patterns:
  transaction_handling:
    begin_transaction: "BEGIN\\s*;|START\\s+TRANSACTION\\s*;"
    commit_transaction: "COMMIT\\s*;"
    rollback_available: "ROLLBACK\\s*;"
    
  migration_metadata:
    migration_id: "--\\s*Migration\\s*ID:"
    description: "--\\s*Description:"
    author: "--\\s*Author:"
    date: "--\\s*Date:"

# Rollback Script Requirements
rollback_scripts:
  required: true
  naming_patterns:
    - "{migration_name}_rollback.sql"
    - "{migration_name}.rollback.sql"
    - "rollback_{migration_name}.sql"
    - "{migration_name}_down.sql"
    
  validation:
    must_exist: true
    non_empty: true
    syntax_check: true
    opposite_operations: false  # Phase 0 Prep - simplified
    
  location:
    same_directory: true
    rollback_subdirectory: false

# Migration Impact Assessment
impact_assessment:
  enabled: true
  
  risk_factors:
    drop_table: 3
    drop_column: 2
    truncate_data: 2
    delete_data: 2
    alter_column_type: 1
    add_constraint: 1
    
  risk_levels:
    low: 0
    medium: 2
    high: 4
    
  assessment_criteria:
    affected_tables_count: true
    data_modification: true
    schema_changes: true
    index_operations: true
    
  thresholds:
    high_risk_threshold: 4
    medium_risk_threshold: 2
    max_affected_tables: 10

# Migration Approval Workflow
approval_workflow:
  enabled: false  # Phase 0 Prep - simplified
  
  development:
    required: false
    auto_approve_low_risk: true
    require_manual_high_risk: false
    
  staging:
    required: true
    auto_approve_low_risk: false
    require_manual_high_risk: true
    
  production:
    required: true
    auto_approve_low_risk: false
    require_manual_high_risk: true
    
  approval_methods:
    comment_based: true  # "-- APPROVED by [name] on [date]"
    file_based: false
    external_system: false

# Migration Execution Settings
execution:
  transaction_mode: true
  rollback_on_error: true
  continue_on_warning: true
  
  timeouts:
    migration_timeout_minutes: 30
    statement_timeout_seconds: 300
    lock_timeout_seconds: 30
    
  performance:
    parallel_execution: false  # Phase 0 Prep
    batch_processing: false  # Phase 0 Prep
    progress_reporting: true

# Migration Testing
testing:
  enabled: true
  test_environments: ["development"]
  
  pre_migration_tests:
    backup_verification: true
    rollback_script_validation: true
    dependency_check: true
    
  post_migration_tests:
    schema_validation: true
    data_integrity_check: false  # Phase 0 Prep
    application_tests: false  # Phase 0 Prep
    
  mock_testing:
    simulate_execution: true
    validate_syntax_only: true
    dry_run_mode: true

# Migration Dependencies
dependencies:
  check_enabled: true
  
  types:
    schema_dependencies: true
    data_dependencies: false  # Phase 0 Prep
    application_dependencies: false  # Phase 0 Prep
    
  resolution:
    auto_resolve: false
    require_manual_resolution: true
    dependency_graph: false  # Phase 0 Prep

# Migration Monitoring and Logging
monitoring:
  enabled: true
  log_all_operations: true
  track_performance: true
  
  metrics:
    migration_duration: true
    statements_executed: true
    rows_affected: false  # Phase 0 Prep
    errors_encountered: true
    
  logging:
    detailed_logs: true
    statement_logging: true
    error_logging: true
    performance_logging: true

# Integration with Orchestra System
orchestration:
  enabled: true
  worker_id: "WORKER_1"
  task_id: "PREP-001D"
  
  reporting:
    status_updates: true
    progress_reporting: true
    completion_notification: true
    error_notification: true
    
  boundaries:
    respect_phase_limits: true
    validate_permissions: true
    check_environment_locks: true

# Mock Operations for Phase 0 Prep
mock_operations:
  enabled: true
  simulate_real_migrations: true
  validate_scripts_only: true
  
  simulation:
    execution_time_range: [5, 30]  # seconds
    success_rate: 0.9
    generate_realistic_logs: true
    
  safety:
    no_real_database_modifications: true
    log_mock_operations: true
    validate_scripts_thoroughly: true

# File and Directory Management
file_management:
  migration_directories:
    - "migrations/"
    - "database/migrations/"
    - "sql/migrations/"
    - "db/migrate/"
    
  file_patterns:
    - "*.sql"
    - "*_migration.sql"
    - "migration_*.sql"
    
  organization:
    timestamp_prefixed: true
    sequential_numbering: true
    categorized_directories: false  # Phase 0 Prep

# Error Handling and Recovery
error_handling:
  auto_rollback_on_failure: true
  create_failure_backup: true
  detailed_error_logging: true
  
  recovery_procedures:
    immediate_rollback: true
    notification_on_failure: false  # Phase 0 Prep
    emergency_stop: true
    
  retry_logic:
    enabled: false  # Phase 0 Prep
    max_retries: 0
    retry_delay_seconds: 0